# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 401, 231))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 401, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_1_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1_1.setObjectName("label_1_1")
        self.gridLayout.addWidget(self.label_1_1, 0, 0, 1, 1)
        self.label_1_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1_2.setObjectName("label_1_2")
        self.gridLayout.addWidget(self.label_1_2, 1, 0, 1, 1)
        self.spinBox_1_1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_1_1.setObjectName("spinBox_1_1")
        self.gridLayout.addWidget(self.spinBox_1_1, 0, 1, 1, 1)
        self.spinBox_1_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_1_2.setObjectName("spinBox_1_2")
        self.gridLayout.addWidget(self.spinBox_1_2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 401, 201))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2_1.setObjectName("label_2_1")
        self.gridLayout_2.addWidget(self.label_2_1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 401, 201))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3_2.setObjectName("label_3_2")
        self.gridLayout_3.addWidget(self.label_3_2, 1, 0, 1, 1)
        self.label_3_1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3_1.setObjectName("label_3_1")
        self.gridLayout_3.addWidget(self.label_3_1, 0, 0, 1, 1)
        self.label_3_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3_3.setObjectName("label_3_3")
        self.gridLayout_3.addWidget(self.label_3_3, 2, 0, 1, 1)
        self.lineEdit_3_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_3_1.setObjectName("lineEdit_3_1")
        self.gridLayout_3.addWidget(self.lineEdit_3_1, 0, 1, 1, 1)
        self.lineEdit_3_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_3_2.setObjectName("lineEdit_3_2")
        self.gridLayout_3.addWidget(self.lineEdit_3_2, 1, 1, 1, 1)
        self.lineEdit_3_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_3_3.setObjectName("lineEdit_3_3")
        self.gridLayout_3.addWidget(self.lineEdit_3_3, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(-1, -1, 401, 201))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4_1 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_4_1.setObjectName("label_4_1")
        self.gridLayout_4.addWidget(self.label_4_1, 0, 0, 1, 1)
        self.spinBox_4_1 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_4_1.setObjectName("spinBox_4_1")
        self.gridLayout_4.addWidget(self.spinBox_4_1, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_1_1.setText(_translate("Dialog", "TextLabel"))
        self.label_1_2.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "Tab 1"))
        self.label_2_1.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Página"))
        self.label_3_2.setText(_translate("Dialog", "TextLabel"))
        self.label_3_1.setText(_translate("Dialog", "TextLabel"))
        self.label_3_3.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Página"))
        self.label_4_1.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Página"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
